
name: Publish Python
description: Publish Assets and Report
inputs:
  version:
    description: The published version
    required: true
  following_version:
    description: The following (dev) version
    required: true
  version_bump_script:
    description: The version bump script
    default: hatch version
  product_name:
    description: The name of the product
    required: true
  silk_asset_group:
    description: The Silk Asset Group for the Project
    required: true
  evergreen_project:
    description: The evergreen project name.
    required: true
  working_directory:
    description: The working directory for the action
    default: "."
  tag_template:
    description: The template for the git tag
    default: "${VERSION}"
  token:
    description: The GitHub access token
  dry_run:
    description: Whether this is a dry run
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install hatch
      shell: bash
      run: pipx install hatch
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: all-dist-${{ github.run_id }}
        path: dist/
    - name: Create detached signature for dist files
      uses: mongodb-labs/drivers-github-tools/gpg-sign@v2
      with:
        filenames: dist/*
    - name: Get the evergreen commit
      id: evergreen-commit
      shell: bash
      run: |
        echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    - uses: mongodb-labs/drivers-github-tools/full-report@v2
      with:
        product_name: ${{ inputs.product_name }}
        release_version: ${{ inputs.version }}
        sarif_report_target_ref: ${{ inputs.version }}
        dist_filenames: dist/*
        silk_asset_group: ${{ inputs.silk_asset_group }}
        evergreen_project: ${{ inputs.evergreen_project }}
        evergreen_commit: ${{ steps.evergreen-commit.outputs.commit }}
        token: ${{ inputs.token }}
    - uses: mongodb-labs/drivers-github-tools/upload-s3-assets@v2
      with:
          version: ${{ inputs.version }}
          product_name: ${{ inputs.product_name }}
          dry_run: ${{ inputs.dry_run }}
    - name: Run GitHub Publish script
      shell: bash
      id: publish-script
      run: ${{ github.action_path }}/publish.sh
      env:
        GH_TOKEN: ${{ inputs.token }}
        VERSION: ${{ inputs.version }}
        TAG_TEMPLATE: ${{ inputs.tag_template }}
        PRODUCT_NAME: ${{ inputs.product_name }}
        DRY_RUN: ${{ inputs.dry_run }}
    # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi
    - name: Publish distribution 📦 to PyPI
      if: inputs.dry_run == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Do Not Publish distribution 📦 to PyPI on Dry Run
      if: inputs.dry_run == 'true'
      shell: bash
      run: |
        echo "Dry run, not uploading to PyPI" >> $GITHUB_STEP_SUMMARY
    - name: Ensure a clean repo
      shell: bash
      run: |
        git clean -dffx
        git pull origin ${GITHUB_REF}
    - name: Set following version
      uses: mongodb-labs/drivers-github-tools/bump-version@v2
      if: inputs.dry_run == 'false'
      with:
          version: ${{ inputs.following_version }}
          version_bump_script: ${{ inputs.version_bump_script }}
          working_directory: ${{ inputs.working_directory }}
    - name: Skip Setting following version
      shell: bash
      if: inputs.dry_run == 'true'
      run: |
        echo "Dry run, not setting the following version: ${{ inputs.following_version }}" >> $GITHUB_STEP_SUMMARY
