
name: Publish Python
description: "Publish Assets and Report"
inputs:
  version:
    description: "The published version"
    required: true
  following_version:
    description: "The following (dev) version"
    required: true
  version_bump_script:
    description: "The version bump script"
    required: true
  product_name:
    description: "The name of the product"
    required: true
  silk_asset_group:
    description: The Silk Asset Group for the Project
    required: true
  token:
    description: "The GitHub access token"
    required: true
  dry_run:
    description: "Whether this is a dry run"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: all-dist-${{ github.run_id }}
        path: dist/
    - name: Create detached signature for dist files
      uses: mongodb-labs/drivers-github-tools/gpg-sign@v2
      with:
        filenames: dist/*
    - uses: mongodb-labs/drivers-github-tools/authorized-pub@v2
      with:
        product_name: ${{ inputs.product_name }}
        release_version: ${{ inputs.version }}
        filenames: dist/*
        token: ${{ inputs.token }}
    - uses: mongodb-labs/drivers-github-tools/sbom@v2
      with:
        silk_asset_group: ${{ inputs.silk_asset_group }}
    - name: Generate Sarif Report
      uses: mongodb-labs/drivers-github-tools/code-scanning-export@v2
      with:
        ref: ${{ inputs.version }}
    - name: Generate Compliance Report
      uses: mongodb-labs/drivers-github-tools/compliance-report@v2
      with:
        token: ${{ inputs.token }}
    - name: Run publish script
      shell: bash
      run: ${{github.action_path}}/publish.sh
      env:
        GH_TOKEN: ${{ inputs.token }}
        VERSION: ${{ inputs.version }}
        PRODUCT_NAME: ${{ inputs.product_name }}
        DRY_RUN: ${{ inputs.dry_run }}
    # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi
    - name: Publish distribution 📦 to PyPI
      if: inputs.dry_run == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Set following version
      shell: bash -eux {0}
      run: |
        git clean -dffx
        bash ${{ inputs.version_bump_script }} ${{ inputs.version }}
    - name: Commit the version bump
      uses: mongodb-labs/drivers-github-tools/git-sign@v2
      with:
        command: git commit -a -m \"BUMP ${{ inputs.following_version }}\" -s --gpg-sign=${{ env.GPG_KEY_ID }}
    - name: Push the commit to the source branch
      shell: bash -eux {0}
      run: |
        if [ ${{ inputs.dry_run }} != "true" ]; then
          git push origin --tags
        else
          echo "Not pushing the following_version tag since it is a dry run"
        fi
