name: Augment the SBOM
description: Augments the SBOM for the project
inputs:
  sbom_in_path:
    description: The path of the input sbom file.
    default: sbom.json
  sbom_file_name:
    description: The name of the augmented sbom file.
    default: cyclonedx.sbom.json
  kondukto_sub_project:
    description: The Kondukto sub-project name (appended to the branch name)
    required: false
  ecr_registry:
    description: "The ECR registry to use"
    default: "901841024863.dkr.ecr.us-east-1.amazonaws.com"
  ecr_repository:
    description: "The ECR repository to use"
    default: release-infrastructure/silkbomb:2.0

runs:
  using: composite
  steps:
    - name: Augments the SBOM file and writes it to the release assets and s3 assets folders
      shell: bash
      env:
        SBOM_IN_PATH: ${{ inputs.sbom_in_path }}
        KONDUKTO_SUB_PROJECT: ${{ inputs.kondukto_sub_project }}
        ECR_REGISTRY: ${{ inputs.ecr_registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_repository }}
        SBOM_FILE_NAME: ${{ inputs.sbom_file_name }}
      run: |
        set -eu
        if [ -n "${KONDUKTO_SUB_PROJECT}" ]; then
          KONDUKTO_BRANCH="${GITHUB_REF_NAME}_${KONDUKTO_SUB_PROJECT}"
        else
          KONDUKTO_BRANCH="${GITHUB_REF_NAME}"
        fi
        echo "Generating SBOM file for ${KONDUKTO_BRANCH}..."
        echo "Updating SBOM file..."
        docker run --platform="linux/amd64" -i --rm -v ${RELEASE_ASSETS}:/pwd -v $(pwd):/repo \
          --env-file=${KONDUKTO_ENVFILE} \
          ${ECR_REGISTRY}/${ECR_REPOSITORY} \
          update --sbom-in /repo/${SBOM_IN_PATH} --sbom-out /pwd/cyclonedx.sbom.json --generate-new-serial-number
        echo "Augumenting SBOM file..."
        docker run --platform="linux/amd64" -i --rm -v ${RELEASE_ASSETS}:/pwd -v $(pwd):/repo \
          --env-file=${KONDUKTO_ENVFILE} \
          ${ECR_REGISTRY}/${ECR_REPOSITORY} \
          augment --sbom-in /pwd/cyclonedx.sbom.json --repo ${GITHUB_REPOSITORY} --branch ${KONDUKTO_BRANCH} --sbom-out /pwd/cyclonedx.sbom.json
        cp ${RELEASE_ASSETS}/cyclonedx.sbom.json ${S3_ASSETS}/${SBOM_FILE_NAME}
        echo "Generating SBOM file for ${KONDUKTO_BRANCH}... done."