name: Python Pre-Publish
description: Perform pre-release operations for Python Libraries
inputs:
  version:
    description: The published version
  version_bump_script:
    description: The version bump script
    default: hatch version
  tag_template:
    description: The template for the git tag
    default: "${VERSION}"
  tag_message_template:
    description: The template for the git tag message
    default: "Release ${VERSION}"
  working_directory:
    description: The working directory for the action
    default: "."
  dry_run:
    description: Whether this is a dry run
    required: true

outputs:
  version:
    description: The output version to use
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install hatch
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pipx install hatch
    - name: Handle inputs
      shell: bash
      run: |
        # Handle DRY_RUN
        if [ "${{ inputs.dry_run }}" != "true" ]; then
            export PUSH_CHANGES=true
        else
            export PUSH_CHANGES=false
        fi
        echo "PUSH_CHANGES=$PUSH_CHANGES" >> $GITHUB_ENV
        # Handle version already bumped
        if [ -z "${{ inputs.version }}" ]; then
          VERSION=$(hatch project metadata version)
          echo $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          echo "VERSION=${{ inputs.version}}" >> $GITHUB_ENV
        fi
    - name: Set version
      uses: mongodb-labs/drivers-github-tools/bump-version@v2
      if: ${{ inputs.version }}
      with:
        version: ${{ env.VERSION }}
        version_bump_script: ${{ inputs.version_bump_script }}
        working_directory: ${{ inputs.working_directory }}
        push_commit: ${{ env.PUSH_CHANGES }}
    - name: Tag version
      uses: mongodb-labs/drivers-github-tools/tag-version@v2
      with:
        version: ${{ env.VERSION }}
        tag_template: ${{ inputs.tag_template }}
        tag_message_template: ${{ inputs.tag_message_template }}
        push_tag: ${{ env.PUSH_CHANGES }}
    - name: Handle version
      shell: bash
      id: version
      run: |
        if [ "${{ inputs.dry_run}}" == 'true' ]; then
          echo "version=${{ github.ref }}" >> $GITHUB_OUTPUT
        else
          export VERSION=${{ env.VERSION }}
          export TAG=$(echo "${{ inputs.tag_template }}" | envsubst)
          echo "version=$TAG" >> $GITHUB_OUTPUT
        fi