version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/*"
      - "/*/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"
