name: Bump Version
description: Bump the version and push if not a dry-run
inputs:
  version:
    description: The new version
    required: true
  version_bump_script:
    description: The version bump script
    default: ''
  commit_template:
    description: The template for the git commit message
    default: "BUMP ${VERSION}"
  push_commit:
    description: Whether to push the commit
    default: "true"
  working_directory:
    description: The working directory for the version bump
    default: "."
  artifactory_image:
    description: "Image to use for artifactory"
    default: release-tools-container-registry-local/garasign-git

runs:
  using: composite
  steps:
    - name: Set new version
      if: ${{ inputs.version_bump_script != '' }}
      shell: bash -eux {0}
      working-directory: ${{ inputs.working_directory }}
      run: |
        ${{ inputs.version_bump_script }} ${{ inputs.version }}
    - name: Get the commit message
      shell: bash -eux {0}
      run: |
        export VERSION=${{ inputs.version }}
        export COMMIT_MESSAGE=$(echo "${{ inputs.commit_template }}" | envsubst)
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
    - name: Commit the version bump
      uses: mongodb-labs/drivers-github-tools/git-sign@v2
      with:
        command: git commit -a -m \"${{ env.COMMIT_MESSAGE }}\" -s --gpg-sign=${{ env.GPG_KEY_ID }}
        artifactory_image: ${{ inputs.artifactory_image }}
    - name: Push the commit to the source branch
      shell: bash -eux {0}
      run: |
        if [ ${{ inputs.push_commit }} == "true" ]; then
          git push origin
          echo "Pushed version bump: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        else
          echo "Created version bump (no push): ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        fi
