name: Upload S3 assets
description: Uploads assets from the S3 asset directory
inputs:
  version:
    description: "The published version"
    required: true
  product_name:
    description: "The name of the product"
    required: true
  filenames:
    description: "Files to upload - supports wildcards and glob patterns"
    default: '*'
    required: false
  dry_run:
    description: "Only print files that would be uploaded, but don't upload any files"
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ env.S3_ASSETS }}
      run: |
        if [ "${{ inputs.dry_run }}" == "false" ]; then
          for filename in ${{ inputs.filenames }}; do aws s3 cp ${filename} s3://${AWS_BUCKET}/${{ inputs.product_name }}/${{ inputs.version }}/${filename}; done
        else
          for filename in ${{ inputs.filenames }}; do echo "Would upload ${filename} to ${{ inputs.product_name }}/${{ inputs.version }}/${filename}"; done
          echo "Dry run, skipping S3 Upload of ${{ inputs.filenames }}" >> $GITHUB_STEP_SUMMARY
        fi
