name: "Code scanning export"
description: "Exports code scanning alerts to a SARIF file"

inputs:
  ref:
    description: "The ref to check for code scanning alerts"
    default: ${{ github.ref }}
  output-file:
    description: "The name/path of the output file to write to"
    default: "code-scanning-alerts.json"
  token:
    description: "GitHub token to use for authenticating with this instance of GitHub."
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
