name: Authorized Publication
description: Generate report for authorized publication on distribution channels
inputs:
  product_name:
    description: Name of product
    required: true
  release_version:
    description: The release version
    required: true
  filenames:
    description: Artifact filename(s) to include in the report, can be a glob pattern
    required: true
  token:
    description: The GitHub token for the action
    required: true

runs:
  using: composite
  steps:
    - name: Prepare report
      shell: bash
      run: |
          export GH_TOKEN=${{ inputs.token }}
          NAME=$(gh api users/${{ github.actor }} --jq '.name')
          export REPORT=$S3_ASSETS/authorized_publication.txt
          echo "Product: ${{ inputs.product_name }}" > $REPORT
          echo "Version: ${{ inputs.release_version }}" >> $REPORT
          echo "Releaser: $NAME"  >> $REPORT
          echo "Build Source: GitHub Actions"
          echo "Build Number: ${{ github.run_id }}"
          for filename in ${{ inputs.filenames }}; do
              SHA=$(shasum -a 256 $filename | awk '{print $1;}')
              echo "Filename: $filename"  >> $REPORT
              echo "Shasum: $SHA"  >> $REPORT
          done
