name: Publish Release Asset to S3
description: "Publish Asset to S3"
inputs:
  npm_package_name:
    description: the npm package name
    required: true

outputs:
  package_version:
    description: "the package version"
    value: ${{ steps.get_version_info.outputs.package_version }}
  package_file:
    description: "the package_file"
    value: ${{ steps.get_version_info.outputs.package_file }}
  commit:
    description: "the commit"
    value: ${{ steps.get_version_info.outputs.commit }}

runs:
  using: composite
  steps:
    - name: Get release version and release package file name
      id: get_version_info
      shell: bash
      run: |
        package_version=$(jq --raw-output '.version' package.json)
        echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"
        echo "package_file=${{ inputs.npm_package_name }}-${package_version}.tgz" >> "$GITHUB_OUTPUT"
        echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
