
name: Publish Release Asset to S3
description: "Publish Asset to S3"
inputs:
  version:
    description: "The published version"
    required: true
  product_name:
    description: "The name of the product"
    required: true
  file:
    description: file to upload
    required: true
  dry_run:
    description: "Whether this is a dry run"
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run publish script
      shell: bash
      run: |
        set -eux
        if [ "$DRY_RUN" == "false" ]; then
            echo "Uploading Release Reports"
            TARGET=s3://${AWS_BUCKET}/${PRODUCT_NAME}/${VERSION}/${FILE}
            aws s3 cp $FILE $TARGET
        else
            echo "Dry run, not uploading to S3 or creating GitHub Release"
            echo "Would upload $FILE"
            cat $FILE
        fi
      env:
        VERSION: ${{ inputs.version }}
        PRODUCT_NAME: ${{ inputs.product_name }}
        DRY_RUN: ${{ inputs.dry_run }}
        FILE: ${{ inputs.file }}
