name: Generate a compliance report
description: Generates the compliance report in the S3_ASSETS folder
inputs:
  sbom_name:
    description: The name of the SBOM file in the S3 bucket
    default: cyclonedx.sbom.json
  sarif_name:
    description: The name of the SARIF file in the S3 bucket
    default: code-scanning-alerts.json
  authorized_pub_name:
    description: The name of the Authorized Publication file in the S3 bucket
    default: authorized-publication.txt
  third_party_dependency_tool:
    description: The name of the tool used to track 3rd party dependencies.
    default: Silk
  evergreen_project:
    description: The evergreen project name.
  evergreen_commit:
    description: The commit associated with the evergreen build for the release.
  security_report_location:
    description: The URL or relative git path to the security report
  release_version:
    description: The published version
  token:
    description: The GitHub token for the action
runs:
  using: composite
  steps:
    - name: Generate Compliance Report
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        SBOM_NAME: ${{ inputs.sbom_name }}
        SARIF_NAME: ${{ inputs.sarif_name }}
        AUTHORIZED_PUB_NAME: ${{ inputs.authorized_pub_name }}
        SECURITY_REPORT_LOCATION: ${{ inputs.security_report_location }}
        RELEASE_VERSION: ${{ inputs.release_version }}
        THIRD_PARTY_DEPENDENCY_TOOL: ${{ inputs.third_party_dependency_tool }}
        EVERGREEN_PROJECT: ${{ inputs.evergreen_project }}
        EVERGREEN_COMMIT: ${{ inputs.evergreen_commit }}
      working-directory: "${{ github.action_path }}"
      run: ./generate.sh
