name: Generate a compliance report
description: Generates the compliance report in the S3_ASSETS folder
inputs:
  sbom_name:
    description: The name of the SBOM file in the S3 bucket
    default: cyclonedx.sbom.json
  sarif_name:
    description: The name of the SARIF file in the S3 bucket
    default: code-scanning-alerts.json
  authorized_pub_name:
    description: The name of the Authorized Publication file in the S3 bucket
    default: authorized-publication.txt
  security_report_location:
    description: The URL or relative git path to the security report
  release_version:
    description: The published version
  token:
    description: The GitHub token for the action
runs:
  using: composite
  steps:
    - name: Generate Compliance Report
      shell: bash
      run: |
        set -eux
        if [ -n ${{ inputs.token }} ]; then
          export GH_TOKEN=${{ inputs.token }}
        fi
        export RELEASE_CREATOR=$(gh api users/${{ github.actor }} --jq '.name')
        export SBOM_NAME=${{ inputs.sbom_name }}
        export SARIF_NAME=${{ inputs.sarif_name }}
        export AUTHORIZED_PUB_NAME=${{ inputs.authorized_pub_name }}
        export SECURITY_REPORT_LOCATION=${{ inputs.security_report_location }}
        export RELEASE_VERSION=${{ inputs.release_version }}
        export REPOSITORY=${{ github.repository }}
        bash ${{ github.action_path }}/generate.sh
