name: "Sign artifact using garasign"
description: "Signs a release artifact"
inputs:
  filenames:
    description: "File name(s) to sign, can be a glob pattern"
    required: true
  garasign_username:
    description: "Garasign username"
    required: true
  garasign_password:
    description: "Garasign password"
    required: true
  artifactory_username:
    description: "Artifactory user"
    required: true
  artifactory_password:
    description: "Artifactory password"
    required: true
  artifactory_image:
    description: "Image to use for artifactory"
    default: release-tools-container-registry-local/garasign-gpg
  artifactory_registry:
    description: "Artifactory registry to be used"
    default: artifactory.corp.mongodb.com
  skip_setup:
    description: "Whether to skip setup"
    default: "false"

runs:
  using: composite
  steps:
    - name: Create the envfile
      if: ${{ inputs.skip_setup == 'false' }}
      run: |
        cat << EOF > envfile
        GRS_CONFIG_USER1_USERNAME=${{ inputs.garasign_username }}
        GRS_CONFIG_USER1_PASSWORD=${{ inputs.garasign_password }}
        EOF
      shell: bash

    - name: Log in to artifactory
      if: ${{ inputs.skip_setup == 'false' }}
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ inputs.artifactory_username }}
        password: ${{ inputs.artifactory_password }}
        registry: ${{ inputs.artifactory_registry }}

    - name: "Create detached signature for file"
      run: |
        podman run \
          --env-file=envfile \
          --rm \
          -v $(pwd):$(pwd) \
          -w $(pwd) \
          ${{ inputs.artifactory_registry }}/${{ inputs.artifactory_image }} \
          /bin/bash -c 'gpgloader && for filename in ${{ inputs.filenames }}; do gpg --detach-sign --armor --output ${filename}.sig ${filename}; done'
      shell: bash
