name: Setup
description: "Set up the Release Environment"
inputs:
  aws_role_arn:
    description: "The aws role to acquire"
    required: true
  aws_region_name:
    description: "The aws region to use"
    required: true
  aws_secret_id:
    description: "The name of the aws secret to use"
    required: true
  artifactory_registry:
    description: "Artifactory registry to be used"
    default: artifactory.corp.mongodb.com
  artifactory_image:
    description: "Image to use for artifactory"
    default: release-tools-container-registry-local/garasign-git

runs:
  using: composite
  steps:
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.aws_role_arn }}
      role-session-name: release-session
      aws-region: ${{ inputs.aws_region_name }}
  - name: Set up
    shell: bash
    id: setup
    run: ${{ github.action_path }}/setup.sh
    env:
      ARTIFACTORY_REGISTRY: ${{ inputs.artifactory_registry }}
      ARTIFACTORY_IMAGE: ${{ inputs.artifactory_image }}
      AWS_SECRET_ID: ${{ inputs.aws_secret_id }}
  - uses: actions/checkout@v4
    with:
      token: ${{ steps.setup.outputs.token }}
