name: Setup
description: "Set up the Release Environment"
inputs:
  aws_role_arn:
    description: "The aws role to acquire"
    required: true
  aws_region_name:
    description: "The aws region to use"
    required: true
  aws_secret_id:
    description: "The name of the aws secret to use"
    required: true
  ecr_registry:
    description: "The ECR registry to use"
    default: "901841024863"
  artifactory_username:
    description: "(deprecated) The artifactory username to be used"
  artifactory_registry:
    description: "(deprecated) Artifactory registry to be used"
    default: artifactory.corp.mongodb.com

runs:
  using: composite
  steps:
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
    with:
      role-to-assume: ${{ inputs.aws_role_arn }}
      role-session-name: release-session
      aws-region: ${{ inputs.aws_region_name }}
  - name: Log in to ECR
    uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
    with:
      registries: "${{ inputs.ecr_registry }}"
  - name: Read secrets from AWS Secrets Manager into environment variables
    uses: aws-actions/aws-secretsmanager-get-secrets@5e19ff380d035695bdd56bbad320ca535c9063f2 # v2
    with:
      secret-ids: |
        ${{ inputs.aws_secret_id }}
      parse-json-secrets: true
  - name: Set up
    shell: bash
    id: setup
    run: ${{ github.action_path }}/setup.sh
    env:
      AWS_SECRET_ID: ${{ inputs.aws_secret_id }}
      ECR_REGISTRY: ${{ inputs.ecr_registry }}
