name: Setup
description: "Set up the Release Environment"
inputs:
  aws_role_arn:
    description: "The aws role to acquire"
    required: true
  aws_region_name:
    description: "The aws region to use"
    required: true
  aws_secret_id:
    description: "The name of the aws secret to use"
    required: true
  app_id:
    description: "The GitHub App id"
    required: true
  private_key:
    description: "The GitHub App private key"
    required: true
  artifactory_registry:
    description: "Artifactory registry to be used"
    default: artifactory.corp.mongodb.com
  artifactory_image:
    description: "Image to use for artifactory"
    default: release-tools-container-registry-local/garasign-git
outputs:
  token:
    description: "GitHub installation access token"
    value: ${{ steps.app-token.outputs.token }}

runs:
  using: composite
  steps:
  - uses: actions/create-github-app-token@v1
    id: app-token
    with:
      app-id: ${{ inputs.app_id }}
      private-key: ${{ inputs.private_key }}
  - uses: actions/checkout@v4
    with:
      token: ${{ steps.app-token.outputs.token }}
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.aws_role_arn }}
      role-session-name: release-session
      aws-region: ${{ inputs.aws_region_name }}
  - name: Read secrets from AWS Secrets Manager into environment variables
    uses: aws-actions/aws-secretsmanager-get-secrets@v2
    with:
      secret-ids: |
        ${{ inputs.aws_secret_id }}
      parse-json-secrets: true
  - name: Set up
    shell: bash
    id: setup
    run: ${{ github.action_path }}/setup.sh
    env:
      ARTIFACTORY_REGISTRY: ${{ inputs.artifactory_registry }}
      ARTIFACTORY_IMAGE: ${{ inputs.artifactory_image }}
      AWS_SECRET_ID: ${{ inputs.aws_secret_id }}
