name: "Run git actions in a signing container"
description: "Allows running arbitrary git actions in a container with GPG keys loaded"
inputs:
  command:
    description: "Command to run inside the container"
    required: true
  ecr_repository:
    description: "The ECR repository to use"
    default: release-infrastructure/garasign-git
  artifactory_image:
    description: "(deprecated) Image to use for artifactory"
    default: release-tools-container-registry-local/garasign-git

runs:
  using: composite
  steps:
    - name: "Run git command"
      run: |
        docker run \
          --env-file=$GARASIGN_ENVFILE \
          --rm \
          -v $(pwd):$(pwd) \
          -w $(pwd) \
          ${ECR_REGISTRY}/${{ inputs.ecr_repository }} \
          /bin/bash -c "gpgloader && ${{ inputs.command }}"
      shell: bash
