name: "Run git actions in a signing container"
description: "Allows running arbitrary git actions in a container with GPG keys loaded"
inputs:
  command:
    description: "Command to run inside the container"
    required: true
  ecr_repository:
    description: "The ECR repository to use"
    default: release-infrastructure/garasign-git

runs:
  using: composite
  steps:
    - name: "Run git command"
      run: |
        WORKING_DIR=/home/git-checkout
        docker run \
          --env-file=$GARASIGN_ENVFILE \
          --rm \
          -v $(pwd):$WORKING_DIR \
          -w $WORKING_DIR \
          ${ECR_REGISTRY}/${{ inputs.ecr_repository }} \
          /bin/bash -c "git config --global --add safe.directory $WORKING_DIR && gpgloader && ${{ inputs.command }}"
      shell: bash
