name: Pre Publish
description: Pre Publish Action for Go Driver
inputs:
  version:
    description: The published version
    required: true
  push_changes:
    description: Whether to push the changes
    default: "true"

runs:
  using: composite
  steps:
    - uses: mongodb-labs/drivers-github-tools/bump-version@v2
      with:
        version: ${{ inputs.version }}
        version_bump_script: "go run ${{ github.action_path }}/bump-version.go"
        commit_template: "BUMP v${VERSION}"
        push_commit: ${{ inputs.push_changes }}
    - uses: mongodb-labs/drivers-github-tools/tag-version@v2
      with:
        version: v${{ inputs.version }}
        push_tag: ${{ inputs.push_changes }}