name: Pre Publish
description: Pre Publish Action for Go Driver
inputs:
  version:
    description: The published version
    required: true
  push_changes:
    description: Whether to push the changes
    default: "true"
  ignored_branches:
    description: Branches to ignore when merging up changes
    required: true

runs:
  using: composite
  steps:
    - uses: mongodb-labs/drivers-github-tools/bump-version@v2
      with:
        version: ${{ inputs.version }}
        version_bump_script: "go run ${{ github.action_path }}/bump-version.go"
        commit_template: "BUMP v${VERSION}"
        # Never push commit, we still need to merge up if a push is requested
        push_commit: false
    - uses: mongodb-labs/drivers-github-tools/tag-version@v2
      with:
        version: v${{ inputs.version }}
        push_tag: ${{ inputs.push_changes }}
    - name: "Determine branch to merge up to"
      if: ${{ inputs.push_changes }}
      id: get-next-branch
      uses: alcaeus/automatic-merge-up-action/get-next-branch@a43d2c2d3ed5a92a1fce3e3bde21c27c578f50d3 #1.0.0
      with:
        ref: ${{ github.ref_name }}
        branchNamePattern: 'release/<major>.<minor>'
        devBranchNamePattern: 'v<major>'
        fallbackBranch: 'master'
        ignoredBranches: ${{ inputs.ignored_branches }}
    - name: "Manually merge up changes"
      if: ${{ inputs.push_changes && steps.get-next-branch.outputs.hasNextBranch }}
      shell: bash
      run: |
        git checkout ${NEXT_BRANCH}
        git merge --strategy=ours ${RELEASE_BRANCH}
        git push origin ${NEXT_BRANCH}
        git checkout ${RELEASE_BRANCH}
        git push origin ${RELEASE_BRANCH}
      env:
        NEXT_BRANCH: ${{ steps.get-next-branch.outputs.branchName }}
        RELEASE_BRANCH: ${{ github.ref_name }}
