name: "Sign artifact(s) using garasign"
description: "Signs release artifact(s)"
inputs:
  filenames:
    description: "File name(s) to sign, can be a glob pattern"
    required: true
  artifactory_image:
    description: "Image to use for artifactory"
    default: release-tools-container-registry-local/garasign-gpg

runs:
  using: composite
  steps:
    - name: "Create detached signature for file"
      shell: bash
      run: |
        podman run \
          --env-file=$GARASIGN_ENVFILE \
          --rm \
          -v $(pwd):$(pwd) \
          -w $(pwd) \
          ${ARTIFACTORY_REGISTRY}/${{ inputs.artifactory_image }} \
          /bin/bash -c 'gpgloader && for filename in ${{ inputs.filenames }}; do gpg --detach-sign --armor --output ${filename}.sig ${filename}; done'

    - name: "Move the signature files to the release directory"
      shell: bash
      run: |
        for filename in ${{ inputs.filenames }}; do mv ${filename}.sig $RELEASE_ASSETS; done
