name: "Sign artifact(s) using garasign"
description: "Signs release artifact(s)"
inputs:
  filenames:
    description: "File name(s) to sign, can be a glob pattern"
    required: true

runs:
  using: composite
  steps:
    - name: "Create detached signature for file"
      shell: bash
      run: |
        podman run \
          --env-file=$GARASIGN_ENVFILE \
          --rm \
          -v $(pwd):$(pwd) \
          -w $(pwd) \
          ${ARTIFACTORY_REGISTRY}/${ARTIFACTORY_IMAGE} \
          /bin/bash -c 'gpgloader && for filename in ${{ inputs.filenames }}; do gpg --detach-sign --armor --output ${filename}.sig ${filename}; done'

    - name: "Move the signature files to the release directory"
      shell: bash
      run: |
        mv ${{inputs.filenames}}.sig $RELEASE_ASSETS
