name: Publish Ruby
description: Generate and publish gems, signatures, and assets for MongoDB Ruby projects
inputs:
  app_id:
    description: The APP_ID defined for this project
    required: true
    type: string
  app_private_key:
    description: The APP_PRIVATE_KEY defined for this project
    required: true
    type: string
  aws_role_arn:
    description: The AWS_ROLE_ARN defined for this project
    required: true
    type: string
  aws_region_name:
    description: The AWS_REGION_NAME defined for this project
    required: true
    type: string
  aws_secret_id:
    description: The AWS_SECRET_ID defined for this project
    required: true
    type: string
  dry_run:
    description: Whether this is a dry run or not ("false" for releases)
    required: true
    type: string
  gem_name:
    description: The name (sans extension) of the gemspec file (e.g. "mongo")
    required: true
    type: string
  product_name:
    description: The name of the product being published (e.g. "Ruby Driver")
    required: true
    type: string
  product_id:
    description: The identifier of the product being published (e.g. "mongo-ruby-driver")
    required: true
    type: string
  release_message_template:
    description: The template for the release message. Use "{0}" in the text to refer to the current version.
    required: true
    type: string
  silk_asset_group:
    description: The Silk asset group for the project
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: "Create temporary app token"
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.app_private_key }}

    - name: "Store GitHub token in environment"
      shell: bash
      run: echo "GH_TOKEN=${{ steps.app-token.outputs.token }}" >> "$GITHUB_ENV"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ env.GH_TOKEN }}

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Get the release version
      shell: bash
      run: echo "RELEASE_VERSION=$(rake version)" >> "$GITHUB_ENV"

    - name: Setup GitHub tooling for DBX Drivers
      uses: mongodb-labs/drivers-github-tools/setup@v2
      with:
        aws_role_arn: ${{ inputs.aws_role_arn }}
        aws_region_name: ${{ inputs.aws_region_name }}
        aws_secret_id: ${{ inputs.aws_secret_id }}

    - name: Set output gem file name
      shell: bash
      run: |
        echo "GEM_FILE_NAME=${{ inputs.gem_name }}-${{ env.RELEASE_VERSION }}.gem" >> "$GITHUB_ENV"

    - name: Build the gem
      shell: bash
      run: |
        gem build --output=${{ env.GEM_FILE_NAME }} ${{ inputs.gem_name }}.gemspec

    - name: Sign the gem
      uses: mongodb-labs/drivers-github-tools/gpg-sign@v2
      with:
        filenames: '${{ env.GEM_FILE_NAME }}'

    - name: Generate authorized publication Documentation
      uses: mongodb-labs/drivers-github-tools/authorized-pub@v2
      with:
        product_name: ${{ inputs.product_name }}
        release_version: ${{ env.RELEASE_VERSION }}
        filenames: ${{ env.GEM_FILE_NAME }}
        token: ${{ env.GH_TOKEN }}

    - name: Download SBOM file from Silk
      uses: mongodb-labs/drivers-github-tools/sbom@v2
      with:
        silk_asset_group: ${{ inputs.silk_asset_group }}

    - name: Generate Sarif Report
      uses: mongodb-labs/drivers-github-tools/code-scanning-export@v2
      with:
        output-file: ${{ env.S3_ASSETS }}/code-scanning-alerts.json

    - name: Generate Compliance Report
      uses: mongodb-labs/drivers-github-tools/compliance-report@v2
      with:
        token: ${{ env.GH_TOKEN }}

    - name: Create and sign the tag
      uses: mongodb-labs/drivers-github-tools/git-sign@v2
      with:
        command: "git tag -u ${{ env.GPG_KEY_ID }} -m 'Release tag for v${{ env.RELEASE_VERSION }}' v${{ env.RELEASE_VERSION }}"

    - name: Push the tag to the repository
      shell: bash
      run: |
        git push origin v${{ env.RELEASE_VERSION }}

    - name: Create a new release
      shell: bash
      run: gh release create v${{ env.RELEASE_VERSION }} --title ${{ env.RELEASE_VERSION }} --generate-notes --draft

    - name: Capture the changelog
      shell: bash
      run: gh release view v${{ env.RELEASE_VERSION }} --json body --template '{{ .body }}' >> changelog

    - name: Prepare release message
      shell: bash
      run: |
        echo "${{ format(inputs.release_message_template, env.RELEASE_VERSION) }}" > release-message
        cat changelog >> release-message

    - name: Update release information
      shell: bash
      run: |
        echo "RELEASE_URL=$(gh release edit v${{ env.RELEASE_VERSION }} --notes-file release-message)" >> "$GITHUB_ENV"

    - name: Upload release artifacts
      shell: bash
      run: gh release upload v${{ env.RELEASE_VERSION }} ${{ env.GEM_FILE_NAME }} ${{ env.RELEASE_ASSETS }}/${{ env.GEM_FILE_NAME }}.sig

    - name: Upload S3 assets
      uses: mongodb-labs/drivers-github-tools/upload-s3-assets@v2
      with:
        version: ${{ env.RELEASE_VERSION }}
        product_name: ${{ inputs.product_id }}
        dry_run: ${{ inputs.dry_run }}

    - name: Publish the gem
      uses: rubygems/release-gem@v1
      if: inputs.dry_run == 'false'
      with:
        await-release: false
