name: Publish Ruby
description: Publish gems, signatures, and assets for MongoDB Ruby projects
inputs:
  app_id:
    description: The APP_ID defined for this project
    required: true
  app_private_key:
    description: The APP_PRIVATE_KEY defined for this project
    required: true
  aws_role_arn:
    description: The AWS_ROLE_ARN defined for this project
    required: true
  aws_region_name:
    description: The AWS_REGION_NAME defined for this project
    required: true
  aws_secret_id:
    description: The AWS_SECRET_ID defined for this project
    required: true
  bundler_cache_version:
    description: The cache-version to use for the bundler cache
    required: false
    default: '0'
  dry_run:
    description: Whether this is a dry run or not ("false" for releases)
    required: true
  gem_name:
    description: The name (sans extension) of the gemspec file (e.g. "mongo")
    required: true
  product_name:
    description: The name of the product being published (e.g. "Ruby Driver")
    required: true
  product_id:
    description: The identifier of the product being published (e.g. "mongo-ruby-driver")
    required: true
  ref:
    description: The reference to checkout (branch, tag, sha, etc)
    required: true
  release_message:
    description: The (markdown-formatted) text to post as the description of the new release
    required: true
  rubygems_version:
    description: The version of Rubygems to use (see setup-ruby/action.yml)
    required: false
    default: latest
  ruby_version:
    description: The version of Ruby to use (see setup-ruby/action.yml)
    default: '3.2'
    required: false
  silk_asset_group:
    description: The Silk asset group for the project
    required: true

runs:
  using: composite
  steps:
    - name: Check out the repository
      # 58501b85eae697e451b5d1d7dba53f69f65d1909 => the 'v2' tag as of 2025-07-28
      uses: mongodb-labs/drivers-github-tools/secure-checkout@58501b85eae697e451b5d1d7dba53f69f65d1909
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.app_private_key }}
        ref: ${{ inputs.ref }}
        submodules: true

    - name: Setup Ruby
      # bb6434c747fa7022e12fa1cae2a0951fcffcff26 => the 'v1' branch as of 2025-07-28
      uses: ruby/setup-ruby@bb6434c747fa7022e12fa1cae2a0951fcffcff26
      with:
        ruby-version: ${{ inputs.ruby_version }}
        rubygems: ${{ inputs.rubygems_version }}
        bundler-cache: true
        cache-version: ${{ inputs.bundler_cache_version }}

    - name: Get the release version
      id: release_version
      shell: bash
      run: echo "version=$(bundle exec rake version)" >> "$GITHUB_OUTPUT"

    - name: Setup GitHub tooling for DBX Drivers
      # 58501b85eae697e451b5d1d7dba53f69f65d1909 => the 'v2' tag as of 2025-07-28
      uses: mongodb-labs/drivers-github-tools/setup@58501b85eae697e451b5d1d7dba53f69f65d1909
      with:
        aws_role_arn: ${{ inputs.aws_role_arn }}
        aws_region_name: ${{ inputs.aws_region_name }}
        aws_secret_id: ${{ inputs.aws_secret_id }}

    - name: Fetch the gem artifacts
      # d3f86a106a0bac45b974a628896c90dbdf5c8093 => the 'v4' tag as of 2025-07-28
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
      with:
        merge-multiple: true

    - name: Sign the gems
      # 58501b85eae697e451b5d1d7dba53f69f65d1909 => the 'v2' tag as of 2025-07-28
      uses: mongodb-labs/drivers-github-tools/gpg-sign@58501b85eae697e451b5d1d7dba53f69f65d1909
      with:
        filenames: '*.gem'

    - name: Generate SSDLC Reports
      # 58501b85eae697e451b5d1d7dba53f69f65d1909 => the 'v2' tag as of 2025-07-28
      uses: mongodb-labs/drivers-github-tools/full-report@58501b85eae697e451b5d1d7dba53f69f65d1909
      with:
        product_name: ${{ inputs.product_name }}
        release_version: ${{ steps.release_version.outputs.version }}
        dist_filenames: '*.gem'
        silk_asset_group: ${{ inputs.silk_asset_group }}

    - name: Look for existing tag
      id: tag_exists
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.release_version.outputs.version }}
      run: |
        if git rev-parse "v${RELEASE_VERSION}" >/dev/null 2>&1; then
          echo "Tag v${RELEASE_VERSION} already exists."
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "Tag v${RELEASE_VERSION} does not exist."
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Create the tag
      # 58501b85eae697e451b5d1d7dba53f69f65d1909 => the 'v2' tag as of 2025-07-28
      uses: mongodb-labs/drivers-github-tools/tag-version@58501b85eae697e451b5d1d7dba53f69f65d1909
      if: steps.tag_exists.outputs.exists == 'false'
      with:
        version: ${{ steps.release_version.outputs.version }}
        tag_template: "v${VERSION}"
        tag_message_template: "Release tag for v${VERSION}"

    - name: Look for existing release
      id: release_exists
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.release_version.outputs.version }}
      run: |
        if gh release view "v${RELEASE_VERSION}" >/dev/null 2>&1; then
          echo "Release v${RELEASE_VERSION} already exists."
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "Release v${RELEASE_VERSION} does not exist."
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Write release notes to file
      shell: bash
      env:
        RELEASE_NOTES: ${{ inputs.release_message }}
      run: |
        # identifier is intentionally obscure to avoid potential conflicts
        # with supplied text from the release notes themselves.
        cat <<__RELEASE_NOTES_IKDJAIELD__ > release_notes.txt
        ${RELEASE_NOTES}
        __RELEASE_NOTES_IKDJAIELD__

    - name: Create a new release
      if: steps.release_exists.outputs.exists == 'false'
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.release_version.outputs.version }}
      run: gh release create v${RELEASE_VERSION} --title ${RELEASE_VERSION} --notes-file release_notes.txt --draft

    - name: Else update the existing release
      if: steps.release_exists.outputs.exists == 'true'
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.release_version.outputs.version }}
      run: gh release edit v${RELEASE_VERSION} --notes-file release_notes.txt

    - name: Upload release artifacts
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.release_version.outputs.version }}
        RELEASE_ASSETS: ${{ env.RELEASE_ASSETS }}
      run: gh release upload --clobber v${RELEASE_VERSION} *.gem ${RELEASE_ASSETS}/*.sig

    - name: Upload S3 assets
      # 58501b85eae697e451b5d1d7dba53f69f65d1909 => the 'v2' tag as of 2025-07-28
      uses: mongodb-labs/drivers-github-tools/upload-s3-assets@58501b85eae697e451b5d1d7dba53f69f65d1909
      with:
        version: ${{ steps.release_version.outputs.version }}
        product_name: ${{ inputs.product_id }}
        dry_run: ${{ inputs.dry_run }}

    - name: Look for existing gem
      id: gem_exists
      shell: bash
      env:
        GEM_NAME: ${{ inputs.gem_name }}
        RELEASE_VERSION: ${{ steps.release_version.outputs.version }}
      run: |
        if gem search --remote ${GEM_NAME} --version ${RELEASE_VERSION} | grep -q "${RELEASE_VERSION}"; then
          echo "Gem ${GEM_NAME} version ${RELEASE_VERSION} already exists."
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "Gem ${GEM_NAME} version ${RELEASE_VERSION} does not exist."
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Publish the gem
      # ebe1ec66bd8d2c709ac29aa2b43438d450e7a0a6 => the 'v1' branch as of 2025-07-28
      uses: rubygems/release-gem@ebe1ec66bd8d2c709ac29aa2b43438d450e7a0a6
      if: inputs.dry_run == 'false' && steps.gem_exists.outputs.exists == 'false'
      with:
        await-release: false

    - name: Publish the release
      if: inputs.dry_run == 'false'
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.release_version.outputs.version }}
      run: gh release edit v${RELEASE_VERSION} --draft=false

