name: Bump Version
description: Bump the version and push if not a dry-run
inputs:
  version:
    description: The new version
    required: true
  tag_template:
    description: The template for the git tag
    default: "${VERSION}"
  tag_message_template:
    description: The template for the git tag message
    default: "Release ${VERSION}"
  push_tag:
    description: Whether to push the tag
    default: "true"
  ecr_repository:
    description: "The ECR repository to use"
    default: release-infrastructure/garasign-git

runs:
  using: composite
  steps:
    - name: Get the tag
      shell: bash -eux {0}
      run: |
        export VERSION=${{ inputs.version }}
        export TAG=$(echo "${{ inputs.tag_template }}" | envsubst)
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: Get the tag message
      shell: bash -eux {0}
      run: |
        export VERSION=${{ inputs.version }}
        export TAG_MESSAGE=$(echo "${{ inputs.tag_message_template }}" | envsubst)
        echo "TAG_MESSAGE=$TAG_MESSAGE" >> $GITHUB_ENV
    - name: Tag the version
      uses: mongodb-labs/drivers-github-tools/git-sign@v3
      with:
        command: git tag -a "${{ env.TAG }}" -m "${{ env.TAG_MESSAGE }}" -s --local-user=${{ env.GPG_KEY_ID }}
        ecr_repository: ${{ inputs.ecr_repository }}
    - name: Verify the tag
      shell: bash -eux {0}
      run: |
        if [ -n "$GPG_PUBLIC_URL" ]; then
          curl $GPG_PUBLIC_URL --output /tmp/signature.pub
          gpg --import /tmp/signature.pub
          git verify-tag $TAG
        else
          echo "Skipping tag verification"
        fi
    - name: Push the tag to the source branch
      shell: bash -eux {0}
      run: |
        if [ ${{ inputs.push_tag }} == "true" ]; then
          git push origin tag $TAG
          echo "Pushed tag: ${{ env.TAG }}" >> $GITHUB_STEP_SUMMARY
        else
          echo "Created tag (no push): ${{ env.TAG }}" >> $GITHUB_STEP_SUMMARY
        fi
