name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        working-directory:
          - code-scanning-export

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ matrix.working-directory }}/.node-version
          cache: npm
          cache-dependency-path: ${{ matrix.working-directory }}/package-lock.json

      - name: Install Dependencies
        id: npm-ci
        working-directory: ${{ matrix.working-directory }}
        run: npm ci

      - name: Check Format
        id: npm-format-check
        working-directory: ${{ matrix.working-directory }}
        run: npm run format:check

      - name: Lint
        id: npm-lint
        working-directory: ${{ matrix.working-directory }}
        run: npm run lint

      - name: Test
        id: npm-ci-test
        working-directory: ${{ matrix.working-directory }}
        run: npm run ci-test
