name: Tests

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -eux {0}

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            persist-credentials: false
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        with:
            extra_args: --all-files --hook-stage manual